---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-api
  ports:
  - name: {{ .Chart.Name }}-api
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-discord
  labels:
    app: {{ .Chart.Name }}-discord
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-discord
  ports:
  - name: {{ .Chart.Name }}-discord
    port: 80
    protocol: TCP
---